### ISSUE TITLE
cpu 爆满    

### ISSUE THREAD

**Issue by heishen666** [hongyaohongyao/smart_classroom#2]
python demo_inference.py --vis --webcam 0  运行后  六核心 笔记本直接拉满卡顿。
遂换台 16核32线程跑代码。占用百分之80.   画面识别卡顿 
![image](https://user-images.githubusercontent.com/55523175/121221728-6c36cb00-c8b8-11eb-9e83-d3b5eec0128f.png)

**Comment by hongyaohongyao** [comment]
笔记本的gpu跑个2-3fps是正常现象

**Comment by heishen666** [comment]
台式机  :
 3900x 12核 24线程     cpu占用  80%
显卡 RTX 3060TI   占用百分之一 。
GPU占用上不来啊

**Comment by hongyaohongyao** [comment]
> 台式机 :
> 3900x 12核 24线程 cpu占用 80%
> 显卡 RTX 3060TI 占用百分之一 。
> GPU占用上不来啊 这配置画面也卡的不行 。。。

多少fps？

**Comment by heishen666** [comment]
![image](https://user-images.githubusercontent.com/55523175/121223311-f92e5400-c8b9-11eb-9a89-1c6d0682093f.png)

**Comment by heishen666** [comment]
288it [06:07,  1.28s/it]
37it [00:47,  1.27s/it]
1fps    。。。。。。。   是需要改什么设置么

**Comment by hongyaohongyao** [comment]
> 288it [06:07, 1.28s/it]
> 37it [00:47, 1.27s/it]
> 1fps 。。。。。。。 是需要改什么设置么 。。这配置不应该啊
你--gpus 设置为0了吗？

**Comment by heishen666** [comment]
python demo_inference.py --vis --webcam 0 --gpus 1  运行还是很卡啊。。。
能加您个联系方式么

**Comment by hongyaohongyao** [comment]
> python demo_inference.py --vis --webcam 0 --gpus 1 运行还是很卡啊。。。
> 能加您个联系方式么

qq：1207105686

**Comment by heishen666** [comment]
已加

**Comment by hongyaohongyao** [comment]
> 已加

发错了，是 1207105685😂

**Comment by FrozenZero** [comment]
> 已加

朋友，后面有找到原因么？我win10，3090的显卡 ，12物理核心 ，资源占用也不突出，但fps上不去，应用卡的十来秒才动一下 @hongyaohongyao @heishen666

**Comment by hongyaohongyao** [comment]
> > 已加
> 
> 朋友，后面有找到原因么？我win10，3090的显卡 ，12物理核心 ，资源占用也不突出，但fps上不去，应用卡的十来秒才动一下 @hongyaohongyao @heishen666

这个和alphapose的流水线处理有关，你需要手动调一下这些参数来平衡各个线程的处理速度，否则数据在处理队列堆积就会在感觉上比较卡顿。不过alphapose这方面处理的感觉不是很好，我已经另外写了一个项目并重写了这部分逻辑。
![image](https://user-images.githubusercontent.com/43579107/124464383-b7180580-ddc6-11eb-89d2-dc8ca8222f16.png)

**Comment by FrozenZero** [comment]
> > > 已加
> > 
> > 
> > 朋友，后面有找到原因么？我win10，3090的显卡 ，12物理核心 ，资源占用也不突出，但fps上不去，应用卡的十来秒才动一下 @hongyaohongyao @heishen666
> 
> 这个和alphapose的流水线处理有关，你需要手动调一下这些参数来平衡各个线程的处理速度，否则数据在处理队列堆积就会在感觉上比较卡顿。不过alphapose这方面处理的感觉不是很好，我已经另外写了一个项目并重写了这部分逻辑。
> ![image](https://user-images.githubusercontent.com/43579107/124464383-b7180580-ddc6-11eb-89d2-dc8ca8222f16.png)

我尝试调试过了这俩参数，按您的方法，或者扩大比例，或者缩小，都试了，发现fps还是极低。
6it [01:07, 15.66s/it]
 python3.6.8 +torch 1.8.1+cu111+opencv-python4.5.1.48
是否是我其他的地方没配置好，或者压根就没怎么使用到gpu
![image](https://user-images.githubusercontent.com/20189238/124468408-a322d280-ddcb-11eb-809a-98ee3ecff002.png)
![image](https://user-images.githubusercontent.com/20189238/124468437-ad44d100-ddcb-11eb-8c53-2484fb070387.png)

**Comment by hongyaohongyao** [comment]
> > > > 已加
> > > 
> > > 
> > > 朋友，后面有找到原因么？我win10，3090的显卡 ，12物理核心 ，资源占用也不突出，但fps上不去，应用卡的十来秒才动一下 @hongyaohongyao @heishen666
> > 
> > 
> > 这个和alphapose的流水线处理有关，你需要手动调一下这些参数来平衡各个线程的处理速度，否则数据在处理队列堆积就会在感觉上比较卡顿。不过alphapose这方面处理的感觉不是很好，我已经另外写了一个项目并重写了这部分逻辑。
> > ![image](https://user-images.githubusercontent.com/43579107/124464383-b7180580-ddc6-11eb-89d2-dc8ca8222f16.png)
> 
> 我尝试调试过了这俩参数，按您的方法，或者扩大比例，或者缩小，都试了，发现fps还是极低。
> 6it [01:07, 15.66s/it]
> python3.6.8 +torch 1.8.1+cu111+opencv-python4.5.1.48
> 是否是我其他的地方没配置好，或者压根就没怎么使用到gpu
> ![image](https://user-images.githubusercontent.com/20189238/124468408-a322d280-ddcb-11eb-809a-98ee3ecff002.png)
> ![image](https://user-images.githubusercontent.com/20189238/124468437-ad44d100-ddcb-11eb-8c53-2484fb070387.png)

15fps已经是一个相对较好的水平了，windows上，python由于gil的缘故实际上没有做到真正的并行计算，因此速度会相对再linux上慢一点

**Comment by FrozenZero** [comment]
15.66s/it是否应该理解为15.66秒处理一帧图片呢？能加您个联系方式不？ @hongyaohongyao

**Comment by hongyaohongyao** [comment]
> 15.66s/it是否应该理解为15.66秒处理一帧图片呢？能加您个联系方式不？ @hongyaohongyao
那个单位应该是it/s,你可以加上--vis参数看一下播放效果，有需要可以加我qq 1207105685
