### ISSUE TITLE
4. face boxes 预训练权重

### ISSUE THREAD

**Issue by Taeok-Lee** [hongyaohongyao/smart_classroom#20]
作者您好
4. face boxes 预训练权重这一部分下面的google drive这个链接的文件失效了

**Comment by sugarmeone** [comment]
同问

**Comment by hongyaohongyao** [comment]
这个项目引用的其他项目的链接可能已经失效了，推荐你使用这个项目的代码，里面有我自己的百度云链接https://github.com/hongyaohongyao/smart_classroom_demo
