### ISSUE TITLE
人脸情绪识别

### ISSUE THREAD

**Issue by Dejavusd** [hongyaohongyao/smart_classroom#5]
请问情绪识别和人脸检测的部分在哪呢？

**Comment by hongyaohongyao** [comment]
情绪识别是其他成员的工作，这里暂时只有非机器学习的方法做的一个简单的功能https://github.com/hongyaohongyao/smart_classroom/blob/master/detection_system/utils/attention_by_expression_angle.py
人脸识别的内容集中在这一部分https://github.com/hongyaohongyao/smart_classroom/tree/master/detection_system/face_recog
